# Data Importation

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('Sales_Data/Sales_January_2019.csv')

In [3]:
data.head(30)

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,141234,iPhone,1,700,01/22/19 21:25,"944 Walnut St, Boston, MA 02215"
1,141235,Lightning Charging Cable,1,14.95,01/28/19 14:15,"185 Maple St, Portland, OR 97035"
2,141236,Wired Headphones,2,11.99,01/17/19 13:33,"538 Adams St, San Francisco, CA 94016"
3,141237,27in FHD Monitor,1,149.99,01/05/19 20:33,"738 10th St, Los Angeles, CA 90001"
4,141238,Wired Headphones,1,11.99,01/25/19 11:59,"387 10th St, Austin, TX 73301"
5,141239,AAA Batteries (4-pack),1,2.99,01/29/19 20:22,"775 Willow St, San Francisco, CA 94016"
6,141240,27in 4K Gaming Monitor,1,389.99,01/26/19 12:16,"979 Park St, Los Angeles, CA 90001"
7,141241,USB-C Charging Cable,1,11.95,01/05/19 12:04,"181 6th St, San Francisco, CA 94016"
8,141242,Bose SoundSport Headphones,1,99.99,01/01/19 10:30,"867 Willow St, Los Angeles, CA 90001"
9,141243,Apple Airpods Headphones,1,150,01/22/19 21:20,"657 Johnson St, San Francisco, CA 94016"
10,141244,Apple Airpods Headphones,1,150,01/07/19 11:29,"492 Walnut St, San Francisco, CA 94016"
11,141245,Macbook Pro Laptop,1,1700,01/31/19 10:12,"322 6th St, San Francisco, CA 94016"
12,141246,AAA Batteries (4-pack),3,2.99,01/09/19 18:57,"618 7th St, Los Angeles, CA 90001"
13,141247,27in FHD Monitor,1,149.99,01/25/19 19:19,"512 Wilson St, San Francisco, CA 94016"
14,141248,Flatscreen TV,1,300,01/03/19 21:54,"363 Spruce St, Austin, TX 73301"
15,141249,27in FHD Monitor,1,149.99,01/05/19 17:20,"440 Cedar St, Portland, OR 97035"
16,141250,Vareebadd Phone,1,400,01/10/19 11:20,"471 Center St, Los Angeles, CA 90001"
17,141251,Apple Airpods Headphones,1,150,01/24/19 08:13,"414 Walnut St, Boston, MA 02215"
18,141252,USB-C Charging Cable,1,11.95,01/30/19 09:28,"220 9th St, Los Angeles, CA 90001"
19,141253,AA Batteries (4-pack),1,3.84,01/17/19 00:09,"385 11th St, Atlanta, GA 30301"
20,141254,AAA Batteries (4-pack),1,2.99,01/08/19 11:51,"238 Sunset St, Seattle, WA 98101"
21,141255,USB-C Charging Cable,1,11.95,01/09/19 20:55,"764 11th St, Los Angeles, CA 90001"
22,141256,Google Phone,1,600,01/29/19 10:40,"675 Washington St, Portland, OR 97035"
23,141257,Apple Airpods Headphones,1,150,01/12/19 18:51,"338 Highland St, San Francisco, CA 94016"
24,141258,AA Batteries (4-pack),1,3.84,01/19/19 21:47,"820 1st St, San Francisco, CA 94016"
25,141259,AAA Batteries (4-pack),2,2.99,01/20/19 17:26,"920 Adams St, San Francisco, CA 94016"
26,141260,AAA Batteries (4-pack),1,2.99,01/01/19 22:00,"293 Hill St, San Francisco, CA 94016"
27,141261,USB-C Charging Cable,1,11.95,01/09/19 18:14,"840 Lincoln St, Atlanta, GA 30301"
28,141262,AAA Batteries (4-pack),1,2.99,01/16/19 12:35,"291 Lincoln St, San Francisco, CA 94016"
29,141263,Bose SoundSport Headphones,1,99.99,01/11/19 23:33,"640 Spruce St, Boston, MA 02215"

In [4]:
data.tail()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
9718,150497,20in Monitor,1,109.99,01/26/19 19:09,"95 8th St, Dallas, TX 75001"
9719,150498,27in FHD Monitor,1,149.99,01/10/19 22:58,"403 7th St, San Francisco, CA 94016"
9720,150499,ThinkPad Laptop,1,999.99,01/21/19 14:31,"214 Main St, Portland, OR 97035"
9721,150500,AAA Batteries (4-pack),2,2.99,01/15/19 14:21,"810 2nd St, Los Angeles, CA 90001"
9722,150501,Google Phone,1,600,01/13/19 16:43,"428 Cedar St, Boston, MA 02215"

In [5]:
import glob

In [6]:
import pandas as pd